### PR TITLE
    feat: swagger.enabled default to true 

### PR DESCRIPTION
**Pull request by tisonkun**
This closes https://github.com/apache/pulsar-manager/issues/391.

### CODE REVIEW

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
We should revert version related changes so that this PR can be cherry-picked into branch-0.4.0 without any conflict.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
Enabling this property does not work for me. Could you verify it in your local env?

Here are how I verified.

Terminal 1:

```bash
# Use Java 1.8
./gradlew build -x test
cd build/distributions/
unzip -q pulsar-manager.zip
./bin/pulsar-manager
```

Terminal 2:

```bash
cd front-end
npm run dev
```

Terminal 3:

```bash
$ CSRF_TOKEN=$(curl http://localhost:7750/pulsar-manager/csrf-token)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    36  100    36    0     0    197      0 --:--:-- --:--:-- --:--:--   197
$ echo $CSRF_TOKEN
a242e5e7-40b3-4750-bdcb-c5543d101fed
$ curl -H "X-XSRF-TOKEN: $CSRF_TOKEN"  \
  -H "Cookie: XSRF-TOKEN=$CSRF_TOKEN;" \
  -H 'Content-Type: application/json' \
  -X PUT http://localhost:7750/pulsar-manager/users/superuser \
  -d '{"name": "admin", "password": "apachepulsar", "description": "test", "email": "username@test.org"}'; echo
{"message":"Add super user success, please login"}x
```

**Comment by tisonkun** [comment]
@BewareMyPower how do you identify it's an error? From the source code this is just formal result when you successfully add a user:

https://github.com/apache/pulsar-manager/blob/e4755d040dfbbb5135d5e285bd07f9bf9b43b694/src/main/java/org/apache/pulsar/manager/controller/UsersController.java#L222-L225

**Comment by BewareMyPower** [comment]
Oh, the message (especially "please login") is a bit misleading. Usually I thought no response means "success".

However, I still cannot login with the username and password I registered.

image

```
2023-05-05 18:03:28.332 ERROR 9616 --- [nio-7750-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 3] with root cause

org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 3
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:80) ~[mybatis-3.5.4.jar:3.5.4]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_362]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_362]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_362]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_362]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426) ~[mybatis-spring-2.0.4.jar:2.0.4]
        at com.sun.proxy.$Proxy142.selectOne(Unknown Source) ~[na:na]
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159) ~[mybatis-spring-2.0.4.jar:2.0.4]
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87) ~[mybatis-3.5.4.jar:3.5.4]
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:144) ~[mybatis-3.5.4.jar:3.5.4]
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85) ~[mybatis-3.5.4.jar:3.5.4]
        at com.sun.proxy.$Proxy160.findByUserName(Unknown Source) ~[na:na]
        at org.apache.pulsar.manager.dao.UsersRepositoryImpl.findByUserName(UsersRepositoryImpl.java:45) ~[pulsar-manager.jar:na]
        at org.apache.pulsar.manager.dao.UsersRepositoryImpl$$FastClassBySpringCGLIB$$e4b0cd9a.invoke(<generated>) ~[pulsar-manager.jar:na]
...
```

**Comment by BewareMyPower** [comment]
Oh it seems that I cannot use "admin" as the username. I used another username "testadmin" and it succeeded. Anyway, it's another topic. This PR LGTM.

**Review by BewareMyPower — APPROVED** [review]

**Comment by tisonkun** [comment]
Thanks for your verification!

Then actually, there is no bug to fix. But we can still change the default value to meet the docs:

> To enable swagger UI, set `swagger.enabled=true` in the `application.properties` file. The default value is `true`.

The message and prohibit `admin` manner can be improved later. Perhaps you or I can open issues for them, but they're not blockers for the ongoing 0.4.0 release :)

**Pull request merged**
