### PR TITLE
Support peek messages from pulsar broker

### PR DESCRIPTION
**Pull request by tuteng**
### Motivation

At present, pulsar-manager does not support a peek message. After the pr is merged, pulsar-manager will support a peek message.

### Modifications

* Support peek messages, include the batch message and non-batch message
* Upgrade pulsar-client version to 2.4.2

image

### CODE REVIEW

**Comment by eolivelli** [comment]
Currently pulsar manager is useful for inspecting and managing a cluster.
But actually the user won't access real data.

If you let pulsar manager users access data we will have to think more about security and privacy rules.
In Europe this could be a problem due to GPRS.

In Bookkeeper Visual Manager we are not giving this feature for this reason

**Comment by tuteng** [comment]
@eolivelli 
Thank you for pointing out this problem and providing this feature is based on the following considerations

1. Some users do have this requirement and want to see real data, which is very convenient for debugging business logic. Although it can be completed by create a consumer, it is simpler to click the mouse on the page.

2. For security and privacy, I think after we merge the pr https://github.com/apache/pulsar-manager/pull/238, pulsar-manager will have complete multi-tenant capabilities, user and role binding, role and tenant and other resource bindings, and tenants are completely isolated from tenants. After JWT authentication and authorization are enabled, different users can only see their own resources. Data support TLS encryption will also be supported later. I hope this feature will enter after these pr are merge, then the platform will be improved in terms of security and privacy.

```
In Europe this could be a problem due to GPRS.
```
I don't know much about this, if necessary, I will consider making this feature as an option.

**Comment by sijie** [comment]
@tuteng it might be worth adding a setting to provide the ability to turn off the peek feature in pulsar manager.

**Comment by sijie** [comment]
@tuteng Can you add a flag to allow turning the feature on/off?

**Pull request merged**
