### PR TITLE
add mysql connector dependent

### LINKED ISSUE #411: support mysql connector dependency
The current version does not support mysql connnector dependency

### PR DESCRIPTION
**Pull request by g0715158**
Fixes #411

Master Issue: #411

Describe the modifications you've done.

Support mysql connnector dependency

### CODE REVIEW

**Review by g0715158 — COMMENTED** [review]
Support mysql connnector dependency

**Review by tuteng — CHANGES_REQUESTED** [review]
The mysql license is not compatible with the apache license, so it is not recommended to add this

**Comment by g0715158** [comment]
> The mysql license is not compatible with the apache license, so it is not recommended to add this

Is it appropriate to use mariadb-java-client as a client driver?

**Comment by tisonkun** [comment]
> mariadb-java-client

No. It's LGPL licensed, which is in category X ( cannot be used ) in ASF guidelines - https://www.apache.org/legal/resolved.html#category-x

**Pull request closed without merging**
