### PR TITLE
Added read only user support

### PR DESCRIPTION
**Pull request by skyrocknroll**
* Added read only user support 
@tuteng @eolivelli PTAL

### CODE REVIEW

**Comment by eolivelli** [comment]
Can you explain what it is a "read only" user ?
Is it an user that can only access data without permission to modify Pulsar Manager configuration or is it an user that cannot alter the Pulsar cluster configuration ?

**Comment by skyrocknroll** [comment]
@eoliveli the user that cannot modify pulsar cluster configuration

**Comment by tuteng** [comment]
I am not sure whether it is reasonable to add such a user. There is back-end storage in pulsar-manager. I am implementing simple user management, which can add some roles to these users, divide users according to roles, and determine what permissions users have, etc. With user management, authentication and authorization, we can give full play to pulsar's multi-tenant capability as much as possible. If you have this requirement and are interested, we can realize this content together.

**Comment by skyrocknroll** [comment]
Ok @tuteng Would be interested in the design . Let me know when you start.

**Pull request closed without merging**
